function createfigure(X1, Y1, Z1, X2)
%CREATEFIGURE(X1, Y1, Z1, X2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data
%  X2:  vector of x data

%  Auto-generated by MATLAB on 20-Nov-2015 14:48:52

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',1,'FontSize',16);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-15 15]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-15 15]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-15 15]);
view(axes1,[-153.5 14]);
grid(axes1,'on');
hold(axes1,'all');

% Create plot3
plot3(X1,Y1,Z1);

% Create plot3
plot3(X2,X2,X2,'MarkerFaceColor',[1 0 0],'MarkerSize',8,'Marker','o',...
    'LineStyle','none',...
    'Color',[1 0 0]);

% Create xlabel
xlabel('x','HorizontalAlignment','right','FontSize',16);

% Create ylabel
ylabel('y','FontSize',16,'HorizontalAlignment','left');

% Create zlabel
zlabel('z','FontSize',16);

